### ISSUE TITLE
[Feature] Command to list players on all servers / specific server

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#1]
It would be nice to have a command to list the (number of) players on all servers and/or each specific server. Optimally this command would be available on both Discord and Minecraft.

Examples:

```
/list

[server1 3/20]
- player1
- player2
- player3

[server2 2/24]
- player4
- player5

[server3 0/40]
No one is online
```

```
/list server1

[server1 3/20]
- player1
- player2
- player3
```

The numbers after the server name would be `#current players (out of) #max players allowed` - though this may get tricky with plugins that spoof this.

~~(Off-topic - would `[{username}@{current}] {message}` be the correct way to prefix a player's message with the player's current server? Ex. `[player4@server2] hello world`)~~ See https://github.com/fooooooooooooooo/VelocityDiscord/issues/2
(Also, is this plugin compatible with "global chat" plugins such as [chat](https://github.com/confor/velocity-chat) or [ChatRegulator](https://github.com/4drian3d/ChatRegulator)?)

This is the only Velocity - Discord bridge kept up-to-date, so I really appreciate your work on this :)

**Comment by fooooooooooooooo** [comment]
sorry i never saw github notifications for this, i didnt think anyone would use it, this is a great issue

> (Also, is this plugin compatible with "global chat" plugins such as [chat](https://github.com/confor/velocity-chat) or [ChatRegulator](https://github.com/4drian3d/ChatRegulator)?)

i havent written any code for compatibility with another plugin but ill see what i can do for this

**Comment by unilock** [comment]
It's a great plugin :)

For what it's worth, I've been using [chat](https://github.com/confor/velocity-chat) with this plugin without issue.

**Comment by fooooooooooooooo** [comment]
this issue is resolved right?

**Comment by unilock** [comment]
I'd say so. An in-game `/list` command would be outside the scope of this plugin. (and velocity has one built-in anyway, it's just disabled via player permissions by default. `/glist` i think?)
