### ISSUE TITLE
What for is GUILD_MEMBERS and the Server Members Intent needed?

### ISSUE THREAD

**Issue by voruti** [fooooooooooooooo/VelocityDiscord#13]
`GatewayIntent.GUILD_MEMBERS` is required here: https://github.com/fooooooooooooooo/VelocityDiscord/blob/master/src/main/java/ooo/foooooooooooo/velocitydiscord/discord/Discord.java#L60. What for?

**Comment by fooooooooooooooo** [comment]
spammed intents until it worked 👍

**Comment by voruti** [comment]
As far as I understand it's for adding and removing users to your Discord server. I don't think it's good to enable unnecessary permissions.

I will now compile a version without that intent, to see if it works and then will report back here ...

**Comment by voruti** [comment]
Apparently the `GatewayIntent.GUILD_MEMBERS` is required by `MemberCachePolicy.ALL`.
https://github.com/fooooooooooooooo/VelocityDiscord/blob/a43525da502fe77bf1bf505baf035aebf48a1435/src/main/java/ooo/foooooooooooo/velocitydiscord/discord/Discord.java#L61
But I don't see that this is required?
I compiled it (without both GUILD_MEMBERS and MemberCachePolicy) and everything seems fine.

**Comment by fooooooooooooooo** [comment]
neither are required, i just put in random shit without checking what is necessary

i can remove it or you can pr a change if you'd like
