### ISSUE TITLE
[Bug] Discord -> Minecraft bridge not working - `failed to get member: <member_id>`

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#18]
When a Discord message is sent, it does not show in the Minecraft chat, and the following is printed to Velocity's log:
```
[JDA MainWS-ReadThread/WARN]: failed to get member: <member_id>
```
(with `<member_id>` being the ID of the Discord member sending the message)

I was able to fix this by reverting https://github.com/fooooooooooooooo/VelocityDiscord/commit/c07d0df460453e56640aef78bcaccb2d6c40f327 - but I'm not sure that was the *cause,* since I haven't done much testing...

Note that nothing has been changed in terms of the Discord bot itself (entitlements, server permissions, etc.) since prior to this issue, and that the Minecraft -> Discord bridge has been working fine all the while.

**Comment by fooooooooooooooo** [comment]
might be the cache policy

**Comment by unilock** [comment]
That's what I thought, but I'm not familiar enough with the Discord API to know for sure.

([relevant JDA docs](https://jda.wiki/using-jda/gateway-intents-and-member-cache-policy/))

**Comment by fooooooooooooooo** [comment]
the changes from c07d0df have been reverted for mc > discord mentions so this is probably fixed as a side effect

**Comment by unilock** [comment]
Seems to be working now :)
