### ISSUE TITLE
`enable_mentions` is misleading

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#22]
The Discord bot created by VelocityDiscord can mention members regardless of the value of `enable_mentions`; the player just has to use the appropriate member ID instead of a username.

Also, the bot can mention roles by ID (but not by name), as well as @.everyone and @.here (using the literal strings "@.everyone" and "@.here").
(the dot in "@." is so I don't mention the corresponding GitHub users. poor naming in retrospect, i suppose...)

This can only be disabled Discord-server-side AFAICT (via Discord user permissions)
(I wasn't able to find anything in JDA that would prevent a bot from mentioning others)

The webhook can do the same, but can NOT be controlled by Discord permissions - which can be dangerous if someone finds out they can @.everyone through Minecraft.

This branch fixes that, to a degree, using JDA's `setAllowedMentions()`: https://github.com/unilock/VelocityDiscord/tree/allowmentions

Note that the webhook, too, can mention members by username if `enable_mentions = true`. Otherwise it can only mention members by ID, or not at all if `webhook_users = false` (using the above branch).

My thoughts:
- `enable_mentions` should be renamed to clarify that it only changes whether Minecraft players can mention Discord members *by username;* members can still be mentioned by ID
- Discord username parsing should maybe be enabled by default when `webhook_users` (from the above branch) is `true` (to prevent confusion)
- Alternatively to the above - maybe there's a way to disable mentioning via user ID, role ID, @.everyone and/or @.here entirely plugin-side? As opposed to relying on Discord permissions and/or `setAllowedMentions()`.

**Comment by fooooooooooooooo** [comment]
> Alternatively to the above - maybe there's a way to disable mentioning via user ID, role ID, @.everyone and/or @.here entirely plugin-side? As opposed to relying on Discord permissions and/or setAllowedMentions().
could use regex to match mentions and @ everyone etc similar to how its done for username mentions

**Comment by catter1** [comment]
Same here - I *strongly* would suggest a `disable_all_pings` or something like that. Would love to use this for my server, but since we're planning on Webhooks, we cannot use it unless `@everyone` and such is disabled.

**Comment by fooooooooooooooo** [comment]
fixed this in 13af9fbf1fefda42c3a9dc8d7348393f2e99d3fc

**Comment by fooooooooooooooo** [comment]
@unilock are your other concerns still relevant?

**Comment by unilock** [comment]
My first point is still somewhat relevant; even if `enable_mentions` is false, players can still mention server members by Discord user ID (e.g. `<@013335555666667999>`). I think it would be good to disable that as well when the setting is disabled, if possible.

And I think there could still be some confusion between `enable_mentions` and `webhook_users`; you'd likely expect the latter to always be enabled when the former is. But honestly how it is now should be obvious enough already :)

Otherwise, lgtm!
