### ISSUE TITLE
[Feature] In-game emoji support

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#27]
It would be neat if (custom) emojis used in Discord could be visible in the Minecraft chat.

This is very likely impossible. That being said, there's a server-side Fabric mod that does something vaguely similar:
https://modrinth.com/mod/server-chat-heads

I'm not sure how fonts are handled in Velocity - if they're handled at all. But I figured, with the existence of that mod, it'd be worth mentioning.

(If this *does* pan out, I suppose Discord user avatars could be implemented, too, which would also be pretty neat.)

**Comment by fooooooooooooooo** [comment]
i think this is technically possible, but it would require a lot of work to do for a not very great result

an alternative which i would like to do some day is have an optional clientside mod that could load emotes defined on the server (either manually or through some method to load ones from a discord server) and then render them in the chat

**Comment by unilock** [comment]
> i think this is technically possible, but it would require a lot of work to do for a not very great result

Fair enough; I'll close it as "not planned" XP

> an optional clientside mod that could load emotes defined on the server (either manually or through some method to load ones from a discord server) and then render them in the chat

[Emojiful](https://www.curseforge.com/minecraft/mc-mods/emojiful) already does pretty much exactly that :v
