### ISSUE TITLE
Exclusion of selected subservers.

### ISSUE THREAD

**Issue by Makkuusen** [fooooooooooooooo/VelocityDiscord#34]
A feature that would be great is to be able to exclude certain sub-servers on the velocity network in the config file. I personally have some hidden servers on the same network whose chats I would like to not expose in discord.

**Comment by fooooooooooooooo** [comment]
what about join/leave/switch messages? i could disable those when an excluded server is involved

that could be configurable although it could get complicated

**Comment by fooooooooooooooo** [comment]
done in [a81f101](https://github.com/fooooooooooooooo/VelocityDiscord/commit/a81f10184aeb1fbe2367b1d78f859e0bc6bc8234)

**Comment by Makkuusen** [comment]
> done in [a81f101](https://github.com/fooooooooooooooo/VelocityDiscord/commit/a81f10184aeb1fbe2367b1d78f859e0bc6bc8234)

Thanks! It works great. However I also ran into the issue that what is written in discord shows up on all sub servers, included the excluded ones. You think it would possible to make it so that excluded server don't get any messages sent to them as well?

**Comment by Makkuusen** [comment]
Thanks!
