### ISSUE TITLE
Webhook messages no longer displaying player skins

### ISSUE THREAD

**Issue by tomkimberlin** [fooooooooooooooo/VelocityDiscord#39]
Started happening a few days ago. Some player's skins are shown but most aren't.

**Comment by unilock** [comment]
This is likely due to the default webhook avatar provider, https://crafatar.com/, being down. Simply replace it with something else; the relevant config option is `avatar_url`. (I personally use [Visage](https://visage.surgeplay.com/index.html).)

**Comment by fooooooooooooooo** [comment]
if crafatar isnt working again soon ill update the default provider and document how to fix this somewhere, in the meantime unilock's solution should work
