### ISSUE TITLE
[Feature] Support for death and advancement messages

### ISSUE THREAD

**Issue by F-fengzi** [fooooooooooooooo/VelocityDiscord#4]
Title says it all

**Comment by unilock** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/11802133/184461172-dffef784-2d9a-4055-b47f-b18c6603f8f7.png">

A plugin (by the same dev) already exists for Paper: https://github.com/fooooooooooooooo/yep-paper
I'm thinking of porting that plugin to Fabric, though it'll take some time.

**Comment by F-fengzi** [comment]
Cool thanks for the info!
I do have a Fabric server in my setup (with the other one being Paper)

**Comment by fooooooooooooooo** [comment]
I was going to make plugins for paper and fabric for this purpose but never got around to doing it, but since other people will use this ill work on it

**Comment by fooooooooooooooo** [comment]
forgot i did this but i didnt push the changes and publish the companion mod

**Comment by klutzies** [comment]
Would you consider porting the companion mod to Fabric? Turns out I don't know Java :v

**Comment by fooooooooooooooo** [comment]
what fabric versions should i port to

**Comment by klutzies** [comment]
Maybe it's possible to port to *all* Fabric versions? (1.14+)
I say this because a mod I know of, [MacOS Input Fixes](https://github.com/hamarb123/MCMacOSInputFixes), has done so.
(I'm almost definitely understating how much effort that would take, considering I know very little Java, and even less about modding Minecraft itself.)

If that's too big an undertaking, then I think 1.16.5, 1.18.2, and 1.19.x are the most popular Fabric versions at the moment.

**Comment by unilock** [comment]
Update:
It's *maybe probably* possible to replace the use of Fabric API's `ServerPlayerEvents` (and Iceberg's `CriterionCallback`)  in [`EventListener.java`](https://github.com/unilock/yep-paper/blob/fabric-fix/src/main/java/ooo/foooooooooooo/yep/EventListener.java) with "simple" mixins. But, having recently spent 14 hours writing a very simple two-mixin mod that lets multiple players enter the same bed, it's probably not at all that easy. (That, or I'm inexperienced, at the very least.)

It's almost definitely *not* possible to replace the use of `ServerPlayNetworking` in [`PluginMessenger.java`](https://github.com/fooooooooooooooo/yep-paper/blob/fabric/src/main/java/ooo/foooooooooooo/yep/PluginMessenger.java#L23), however - but that's at least version-agnostic (hopefully).

**Comment by unilock** [comment]
And with that, Bukkit and Fabric are (mostly?) covered.
Forge support when?? ([relevant](https://github.com/adde0109/Ambassador))

**Comment by unilock** [comment]
I ported Yep to Forge.

https://github.com/unilock/yep-forge

@fooooooooooooooo, if you'd like, could you make a Forge branch @ [yep-paper](https://github.com/fooooooooooooooo/yep-paper)? So I can submit a pull request.

**Comment by fooooooooooooooo** [comment]
> .

done

**Comment by fooooooooooooooo** [comment]
i think this is complete
