### ISSUE TITLE
Missing plugin.yml

### ISSUE THREAD

**Issue by tobiasbrae** [fooooooooooooooo/VelocityDiscord#40]
I tried to install this plugin, but on startup the server states that there is no paper-plugin.yml or plugin.yml within the .jar and therefore the plugin can't be loaded.

Paper version: 1.20.2-299
VelocityDiscord Version: 1.8.1

Can anybody tell me what's wrong?

**Comment by unilock** [comment]
Are you sure? I can't find it under "Paper" when filtering by platform.

<img width="1226" alt="image" src="https://github.com/fooooooooooooooo/VelocityDiscord/assets/11802133/53bdcb13-5eda-4f25-b929-3d4dd3509248">
<img width="1226" alt="image" src="https://github.com/fooooooooooooooo/VelocityDiscord/assets/11802133/8c542ae7-3f47-4d08-aa19-2cfadb25b728">
