### ISSUE TITLE
Messages from other webhooks fail with "failed to get member"

### ISSUE THREAD

**Issue by jackmawer** [fooooooooooooooo/VelocityDiscord#42]
With bot messages allowed, webhooks other than the bot's own do not pass through to minecraft chat. The console logs the following:
> [ooo.foooooooooooo.velocitydiscord.VelocityDiscord]: failed to get member: 1212145110175842425

The error appears to be generated [here](https://github.com/fooooooooooooooo/VelocityDiscord/blob/c2abf65e269c1bbc001b23a2ea73883809cdc206/src/main/java/ooo/foooooooooooo/velocitydiscord/discord/MessageListener.java#L73), but I'm not sure why the webhook causes this line to fail.

**Comment by jackmawer** [comment]
According to JDA docs, getMember() can return null if the message was sent by a webhook:
https://github.com/discord-jda/JDA/blob/f90767f7ad7c66f5cdb61a655669af7db62e0be3/src/main/java/net/dv8tion/jda/api/entities/Message.java#L416

**Comment by voruti** [comment]
Discord differentiates users and bots:
> Users are separated by a distinction of "bot" vs "normal."

https://discord.com/developers/docs/resources/user

Webhooks are separate from that:
> They do not require a bot user or authentication to use.

https://discord.com/developers/docs/resources/webhook
