### ISSUE TITLE
Change channel topic in Discord

### ISSUE THREAD

**Issue by Ceddicedced** [fooooooooooooooo/VelocityDiscord#46]
Adding an option that enables changing the topic of the discord channel in which the bot is posting the messages would be nice.

Something like a playlist and currentplayers/maxplayers / tps or something that is periodically updating.

Any thoughts on that?

**Comment by fooooooooooooooo** [comment]
i can implement this, although the update rate on channel topics is limited to 2 updates per 10 minutes

**Comment by Ceddicedced** [comment]
I think even 1 update per 10 minutes is more than enough. Maybe a config option to set the rate limit would be usefull if the update should just occur every 30 min or so.

**Comment by Ceddicedced** [comment]
Created PR #48
