### ISSUE TITLE
LuckPerms Prefix Support

### ISSUE THREAD

**Issue by Skullians** [fooooooooooooooo/VelocityDiscord#49]
Hey, would it be possible to add support for LuckPerms Prefixes?
As of right now in a discord channel it just outputs:
`{server} {player}: {message}`

Would it be possible to add support for LuckPerms prefixes?
So you could do:
`{server} {luckperms_prefix} {player}: {message}`

e.g. `[Survival] OWNER Player: Hello World!`

**Comment by fooooooooooooooo** [comment]
it looks like luckperms can display multiple prefixes at once, do you have any preference on how this should be handled?

https://luckperms.net/wiki/Prefix-&-Suffix-Stacking

**Comment by Skullians** [comment]
Hey, is it possible to display the highest group / prefix by weight (not including the inherited ones)?

**Comment by fooooooooooooooo** [comment]
added in 8a6a4fc

**Comment by Skullians** [comment]
Legend.
