### ISSUE TITLE
[Feature] Allow using Discord embeds for messages

### ISSUE THREAD

**Issue by F-fengzi** [fooooooooooooooo/VelocityDiscord#5]
Configurable embed message with e.g. join/leave, switch server notices

**Comment by fooooooooooooooo** [comment]
@F-fengzi if this is still wanted, can you give an example of what the embed would look like so i have an idea of how it should be implemented

**Comment by voruti** [comment]
I think this means something like this: 
![grafik](https://github.com/fooooooooooooooo/VelocityDiscord/assets/45130096/26b9a59e-2e8c-42d5-9ce7-4da90c8c0d40)

**Comment by F-fengzi** [comment]
I'm personally good with plain messages and the webhook method (currently using it), but just suggesting another option if other users find it preferred.

My thought was that in the plain messages mode, a embed for join/leave/switch/advancement messages would make them more noticeable and separate from the player chats.

I remember there's a site icon and title field that you can use for the player avatar and names. Also you can use different colors for different types of notices (for example green for join, red for leave, gold for advancements, and choose one for switching/etc.)

While on it maybe another option to have player chats in embeds too, I don't think it's important but since other popular Discord bridging plugins use this method by default, there may be users who'd like to keep that setting.

**Comment by Ceddicedced** [comment]
Should be completed now

**Comment by fooooooooooooooo** [comment]
implemented in 46fc72f
