### ISSUE TITLE
LuckPerms missing error on plugin load

### ISSUE THREAD

**Issue by Ceddicedced** [fooooooooooooooo/VelocityDiscord#51]
It seems that for the new PreRelease luckperms in mandatory even though it should be optional.

`com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms `

I think luckerperms should not be imported in the VelocityDiscord.java. I'm not sure how this should be best mitigated. Probably in another java file in a same manner lile the YepListener...

**Comment by fooooooooooooooo** [comment]
fixed in 14f1212
