### ISSUE TITLE
Update Hangar and Modrinth

### ISSUE THREAD

**Issue by Ceddicedced** [fooooooooooooooo/VelocityDiscord#53]
After some patches the version on these providers seem to be little bit outdated.

https://hangar.papermc.io/fooooooooooooooo/VelocityDiscord
https://hangar.papermc.io/fooooooooooooooo/VelocityDiscord

Maybe also CI would be nice. So when a release is created the sites are getting updated.

**Comment by fooooooooooooooo** [comment]
uploaded at
https://modrinth.com/plugin/velocitydiscord/version/ROhWZCMQ
and
https://hangar.papermc.io/fooooooooooooooo/VelocityDiscord/versions/v1.9.0

i skipped making a release for the pre versions becuase they were only meant to be there for a short time
