### ISSUE TITLE
Velocity Discord breaks cross server chat

### ISSUE THREAD

**Issue by LevyWilson** [fooooooooooooooo/VelocityDiscord#56]
We used the plug-in for about half a day and a big issue we ran across was it broke cross server chat via bungeecord. The servers could see their own chat and discord chat, and discord could see all chat, but chat between servers in-game stopped working. It's a shame because Webhooks are awesome for this discord integration stuff, but bungeecord still needs to work. :(

We're running with Velocity 442. Servers include 6 modpack servers, 5 forge and 1 1.21.1 neoforge server in legacy mode due to two 1.12.2 modpacks.

**Comment by LevyWilson** [comment]
Okay, I'm confused. We were using SimpleProxyChat before and that might have been what had enabled cross server chat before for us. I'm going to install Velocity Chat now and test things.

**Comment by LevyWilson** [comment]
Okay, nevermind. I guess I thought the cross-server chat was stock Velocity, but it was something Simple Proxy Chat had been doing all this time. I'm going to try to use both plugins together because VelocityDiscord does the webhooks really well, which is something SPC has neglected to implement.

**Comment by voruti** [comment]
https://github.com/voruti/CopyChat
