### ISSUE TITLE
Suggestion: Server name Aliases

### ISSUE THREAD

**Issue by LevyWilson** [fooooooooooooooo/VelocityDiscord#57]
Any chance a future update could be made to change the server names as they appear for discord chat webhooks? Right now it only uses their names in Velocity, but instead of BW - Username or SMP - Username, I would like to set the plugin to change the server name to something else, like the servers' full names instead of just how they're abbreviated in Velocity. BedWars - Username and Survival - Username for example. Simple Proxy Chat allows this, but doesn't have the fancy looking webhook chat like this plugin does.

**Comment by fooooooooooooooo** [comment]
added in 79eb161

**Comment by LevyWilson** [comment]
Just tested it. Works fantastically, but I had to put the config change in manually.
